language: go

go:
  - 1.7

install:
  - go get -u github.com/golang/dep/...
  - dep ensure
  - go get -t ./...
  - go get github.com/dedis/Coding || true
  - go get golang.org/x/tools/cmd/cover
  - go get github.com/dedis/goveralls

script:
  - make test

notifications:
  email: false
